/**
 * \file wizard_revision.h
 * \author Koch, Roman (koch.roman@gmail.com)
 *
 * Copyright (c) 2023, Roman Koch, koch.roman@gmail.com
 * SPDX-License-Identifier: MIT
 */

/**
    \brief Software revision

    This file was generated by the project management tools.
    ATTENTION: Do not change the file.
*/

#ifndef __WIZARD_REVISION_H__
#define __WIZARD_REVISION_H__

/* \name Software defines */
/* @{ */

/* \name Software identifier */
/* @{ */
#define FIRMWARE_NAME wizard

#define FIRMWARE_MAJOR 1
#define FIRMWARE_MINOR 0
#define FIRMWARE_PATCH 0
#define FIRMWARE_TWEAK 0

#define FIRMWARE_IDENTIFIER (((1+0) << 8) + (0+0))
#define FIRMWARE_REVISION ((0+0) << 8) + (0+0)
#define FIRMWARE_HASH e710
/* @} */

/* \name Revision Macros */
/* @{ */
#define X(name, major, minor, patch, tweak, hash) __X(name, major, minor, patch, tweak, hash)
#define __X(name, major, minor, patch, tweak, hash) #name " " #major "." #minor "." #patch "." #tweak " #" #hash
#define REVISION() X(FIRMWARE_NAME, FIRMWARE_MAJOR, FIRMWARE_MINOR, FIRMWARE_PATCH, FIRMWARE_TWEAK, FIRMWARE_HASH)
#define AUTHOR() "Roman Koch"
#define ADDRESS() "koch.roman@gmail.com"
/* @} */

/* @} */

#endif /* __WIZARD_REVISION_H__ */
